### ISSUE TITLE
Bug: add missing Tailwind logo

### ISSUE THREAD

**Issue by astagi** [oruga-ui/demo-tailwindcss#1]
![image](https://user-images.githubusercontent.com/537363/135317673-62e63da7-375b-4b91-b83a-e58128d5238e.png)

Tailwind logo is disappeared, you need to bring it back on the navigation bar. To do that:

- Insert a new Tailwind logo inside the project
- Load and show it inside the page

Be sure that the logo you use has no legal complications.

**Comment by CinnamonXI** [comment]
Can you assign this to me please?

**Comment by astagi** [comment]
Sure @CinnamonXI thank you for contributing!

**Comment by CinnamonXI** [comment]
fixed: https://github.com/oruga-ui/demo-tailwindcss/pull/3
I hope I did the right thing and satisfy all requirements?
